const IndustryProject1 = require("../../../assets/IndustryProjects-1.png");
const IndustryProject2 = require("../../../assets/IndustryProjects-2.png");
const IndustryProject3 = require("../../../assets/IndustryProjects-3.png");
const IndustryProject4 = require("../../../assets/IndustryProjects-4.png");

const ModalThumbnail1 = require("../../../assets/ModalThumbnail-1.png");
const ModalThumbnail2 = require("../../../assets/ModalThumbnail-2.png");
const ModalThumbnail3 = require("../../../assets/ModalThumbnail-3.png");
const ModalThumbnail4 = require("../../../assets/ModalThumbnail-4.png");

export const IndustryProjectsData = [
  {
    image: IndustryProject1,
    modalThumbnail: ModalThumbnail1,
    title: "Frontline Staff Portal",
    content:
      "<p><strong><span style=font-size:24px>Frontline staff portal</span></strong></p><p><span style=font-size:20px><span style=color:#7d7d7d>Overview</span></span></p><p>The Bank&#39;s Frontline Staff Portal is a web-based application that empowers frontline staff to efficiently respond to customer queries. With a unique card layout, multiple policy management, efficient search functionality, admin view for content management, and version history feature, the portal streamlines workflow, enhances accuracy, and improves customer service.</p><p style=color:#7d7d7d;>Key Features:</p><ol><li>Efficient Policy Management: Simultaneously open and manage multiple policies in a single screen.</li><li>Robust Search Functionality: Quick and accurate search for relevant information, policies, or documents.</li><li>Admin View for Content Management: Review and publish new content efficiently.</li><li>Version History for Content Comparison: Compare different content versions for accuracy and consistency</li></ol><p><span style=color:#7d7d7d><span style=font-size:20px>Technicality</span></span></p><p>The Bank&#39;s Frontline Staff Portal is a web-based application that empowers frontline staff to efficiently respond to customer queries. With a unique card layout, multiple policy management, efficient search functionality, admin view for content management, and version history feature, the portal streamlines workflow, enhances accuracy, and improves customer service.</p><p>&nbsp;</p>",
  },
  {
    image: IndustryProject2,
    modalThumbnail: ModalThumbnail2,
    title: "Chatbot Development",
    content:
      "<p><span style=font-size:24px><strong>Chatbot Development</strong></span></p><p><span style=color:#7d7d7d>Overview</span></p><p>The HR chatbot application is designed to assist employees of a bank with their HR-related queries. It's developed using React.js for the front end and AWS Connect as the backend service. Employees can interact with the chatbot to get answers to their HR-related questions quickly and efficiently. The chatbot provides responses and can seamlessly connect employees with real HR agents if needed.</p><p style=color:#7d7d7d;>Key Features:</p><ol><li>User Interface: The application has a user-friendly interface developed using React.js, allowing employees to easily navigate and interact with the chatbot. AWS Connect Integration: AWS Connect serves as the backend service for handling chatbot interactions, providing scalability and reliability.</li><li>Query Resolution: The chatbot can handle various HR-related queries, including but not limited to leave policies, pay information, performance evaluations, benefits, etc.</li><li>Real-Time Assistance: Employees can get instant responses to their queries, reducing the need for manual intervention.</li><li>Agent Handoff: If the chatbot is unable to resolve a query or if the employee prefers to speak with a real HR agent, the chatbot seamlessly connects them with an available agent.</li><li>Suggested Topics: The chatbot offers suggestions for common topics like leave policies, pay-related questions, performance evaluations, etc., to assist employees in finding the information they need quickly.</li><li>Feedback Mechanism: Employees can provide feedback on the chatbot's responses, helping to improve its accuracy and effectiveness over time.</li><li>Security and Compliance: The application ensures data security and compliance with banking regulations, protecting sensitive employee information.</li></ol><p><span style=color:#7d7d7d;>Technicality</span></p><p>The HR chatbot application provides a convenient and efficient way for employees of the bank to access HR-related information and support.</p><p>&nbsp;</p>",
  },
  {
    image: IndustryProject3,
    modalThumbnail: ModalThumbnail3,
    title: "Knowledge Management",
    content:
      "<p><span style=font-size:24px;><strong>Knowledge Management</strong></span></p><p><span style=color:#7d7d7d;>Overview</span></p><p>The front end React knowledge management project is designed to streamline information management within a SharePoint Online environment. It consists of multiple pages with editable content, facilitated by a rich text editor powered by the TinyMCE React library. The project also features reusable components for easily adding and organizing content, as well as additional functionalities like displaying recent highlights on page versions, a search component for comprehensive page search, and a user question submission system with admin clarification.</p><p style=color:#7d7d7d;>Key Features:</p><ol><li>SharePoint Online Integration: Utilizing SharePoint Online as the platform, the project establishes a structured environment for knowledge management.</li><li>React Frontend: The frontend is built using React, ensuring a dynamic and responsive user experience.</li><li>Editable Pages: Multiple pages are available for content organization, and each page is editable, allowing users to update information as needed.</li><li>Rich Text Editor: The editor web part integrates the TinyMCE React library, providing a user-friendly interface for editing content with rich text formatting capabilities.</li><li>Reusable Components: Various reusable components have been developed to enable easy addition and management of content. These components enhance consistency and efficiency in content creation.</li><li>Version Highlights: Recent highlights on page versions are displayed, offering users insights into recent changes made to pages.</li><li>Search Component: A search feature allows users to search through all pages, enhancing accessibility and navigation within the knowledge base.</li><li>User Question Submission: Users can submit questions through a dedicated page. Admins can then provide clarifications, fostering communication and knowledge sharing within the system.</li></ol><p><span style=color:#7d7d7d;>Technicality</span></p><p>The project utilizes SharePoint REST APIs and the SharePoint Framework (SPFx) to integrate React components seamlessly into SharePoint Online. Components are developed using React and styled with CSS or CSS preprocessors like SASS. They are designed to be modular and reusable across different pages. SharePoint Online handles user authentication. Authorization levels are managed through SharePoint permissions, ensuring that only authorized users can edit content or answer questions.</p><p>&nbsp;</p>",
  },
  {
    image: IndustryProject4,
    modalThumbnail: ModalThumbnail4,
    title: "Internal HR inbox portal",
    content:
      "<p><span style=font-size:24px;><strong>Internal HR inbox portal</strong></span></p><p><span style=color:#7d7d7d;>Overview</span></p><p>The Inbox React component is a part of a larger system with its backend hosted in Workday. This component primarily displays a list of messages received by users. Users can click on any message to view its details in a right panel. The component is designed to be responsive, ensuring usability across different devices and screen sizes.</p><p style=color:#7d7d7d;>Key Features:</p><ol><li>Integration with Workday Backend: The Inbox component integrates with Workday's backend system to fetch and display messages. This integration ensures real-time access to messages stored in Workday.</li><li>Message List Display: Messages are presented in a list format, showing essential details like sender, subject, and timestamp. Users can quickly scan through the list to find relevant messages.</li><li>Message Viewing Panel: Clicking on a message in the list opens a detailed view in the right panel. This view includes the message content along with any attachments or additional information.</li><li>Responsiveness: The component is designed to be responsive, adapting its layout and behavior to different screen sizes and orientations. This ensures a consistent user experience across devices like desktops, tablets, and mobile phones.</li></ol><p><span style=color:#7d7d7d;>Technicality</span></p><p>The Inbox component is developed using React, a JavaScript library for building user interfaces. React's component-based architecture allows for easy creation and management of UI elements. Workday's APIs are utilized to fetch messages from the backend. This integration involves making HTTP requests to Workday's API endpoints to retrieve message data. The list of messages is displayed using a React component, which fetches data from the backend and renders it dynamically. Pagination may be implemented for large message sets. When a message is clicked, the right panel is updated with the detailed view of the selected message. This can be achieved by conditionally rendering components based on user actions. Responsive design is implemented using CSS media queries and flexible layout techniques. CSS frameworks like Bootstrap or Material-UI may be used to expedite the process of creating responsive layouts.</p><p>&nbsp;</p>",
  },
];
